{% set version = "1.11.0" %}
{% set sha256 = "6da762d768f061da720a2acfe0b481f31ef72f88aa10243922789c6ab19d5556" %}

package:
  name: dbus
  version: {{ version }}

source:
  url: http://dbus.freedesktop.org/releases/dbus/dbus-{{ version }}.tar.gz
  sha256:  {{ sha256 }}
  patches:
    - 0001-Add-var-lib-dbus-machine-id-as-a-fallback.patch  # [linux]
    - 0002-Make-it-possible-to-read-files-on-proc-which-reports.patch  # [linux]
    - 0003-Use-proc-sys-kernel-random-boot_id-as-last-resort-fa.patch  # [linux]

build:
  skip: true  # [win]
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - expat
    - python
  run:
    - expat

test:
  commands:
    - dbus-daemon --version
    - dbus-uuidgen

about:
  home: http://www.freedesktop.org/wiki/Software/dbus/
  license: GPL2
  license_file: COPYING
  summary: "Simple message bus system for applications to talk to one another"
  description: |
    D-Bus is a message bus system, a simple way for applications
    to talk to one another. In addition to interprocess communication, D-Bus helps
    coordinate process lifecycle; it makes it simple and reliable to code a "single
    instance" application or daemon, and to launch applications and daemons on
    demand when their services are needed.
  dev_url: git://anongit.freedesktop.org/dbus/dbus
  doc_url: https://www.freedesktop.org/wiki/IntroductionToDBus/
  doc_source_url: https://cgit.freedesktop.org/dbus/dbus/tree/doc

extra:
  recipe-maintainers:
    - mingwandroid
    - ccordoba12
    - nehaljwani
